### ISSUE TITLE
Possible unhandled edge case: translation failed when no new local saves were made

### ISSUE THREAD

**Issue by Vectorial1024** [emipa606/ShowModUpdates#3]
Error message:

```
Could not resolve symbol "1" for string "Found {0} mod-updates since save was made at {1}".
UnityEngine.StackTraceUtility:ExtractStackTrace ()
Verse.Log:Error (string)
Verse.Log:ErrorOnce (string,int)
Verse.GrammarResolverSimple:TryResolveInner (Verse.TaggedString,int,System.Text.StringBuilder,System.Collections.Generic.List`1<string>,System.Collections.Generic.List`1<object>,bool)
Verse.GrammarResolverSimple:Formatted (Verse.TaggedString,System.Collections.Generic.List`1<string>,System.Collections.Generic.List`1<object>)
Verse.GrammarResolverSimpleStringExtensions:Formatted (string,Verse.NamedArgument,Verse.NamedArgument)
Verse.GrammarResolverSimpleStringExtensions:Formatted (Verse.TaggedString,Verse.NamedArgument,Verse.NamedArgument)
Verse.TranslatorFormattedStringExtensions:Translate (string,Verse.NamedArgument,Verse.NamedArgument)
ShowModUpdates.ShowModUpdates:CheckModUpdates ()
ShowModUpdates.ShowModUpdates/<>c:<ReadyToRead>b__15_0 ()
System.Threading.ThreadHelper:ThreadStart_Context (object)
System.Threading.ExecutionContext:RunInternal (System.Threading.ExecutionContext,System.Threading.ContextCallback,object,bool)
System.Threading.ExecutionContext:Run (System.Threading.ExecutionContext,System.Threading.ContextCallback,object,bool)
System.Threading.ExecutionContext:Run (System.Threading.ExecutionContext,System.Threading.ContextCallback,object)
System.Threading.ThreadHelper:ThreadStart ()
```

Local environment:

- fresh install of RImWorld
- saves restored from the cloud
- no new saves made afterwards
- enable a few mods
- enable this mod
- see error occasionally when in title screen

Supposedly in this setup, there is no such "last saved at" information, and then the required string for the translation cannot be found.

**Comment by emipa606** [comment]
Hm, I cant seem to replicate this. 
In my tests it either finds a save and uses that, or if I empty the save-directory it just show the 
"No previous save found, cannot show mod-updates." message

**Comment by Vectorial1024** [comment]
Strangely, I also can't seem to reproduce this. Maybe this is just a freak incident?

When is this `"Found {0} mod-updates since save was made at {1}"` message supposed to be shown? I was only getting onto the title screen, haven't done anything yet, and noticed a "XX updated mods" button on the screen. That button does not seem like this message.

If no one else has any clue then feel free to close this.

**Comment by emipa606** [comment]
Its shown in the log, so in those rare cases when a mod-update crashes the whole game you can still see what mods have updated in the log when searching for a reason.
